-- Volanteo · Bienestar Sonora
-- Backend Supabase para GitHub Pages
-- Ejecutar completo en Supabase > SQL Editor.

create extension if not exists pgcrypto with schema extensions;

-- =========================
-- 1. ADMINISTRACIÓN
-- =========================
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('admin','viewer')),
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where user_id = auth.uid() and role = 'admin'
  );
$$;

-- El estado de planeación conserva la estructura de la web app (Jornadas > ejercicios > rutas > equipos).
create table if not exists public.app_state (
  id text primary key default 'main',
  state jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

-- Credenciales de brigadistas. El PIN nunca se expone por SELECT al frontend de campo.
create table if not exists public.brigadista_credentials (
  brigadista_id text primary key,
  nombre text not null,
  activo boolean not null default true,
  pin_hash text not null,
  updated_at timestamptz not null default now()
);

-- Estado operativo separado del JSON de planeación para no reescribir toda la jornada con cada GPS/reporte.
create table if not exists public.route_runtime (
  route_id text primary key,
  status text not null default 'pending' check (status in ('pending','live','done')),
  completed_blocks integer not null default 0,
  completed_units numeric not null default 0,
  progress integer not null default 0 check (progress between 0 and 100),
  started_at timestamptz,
  finished_at timestamptz,
  last_position jsonb,
  last_position_at timestamptz,
  last_progress_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.route_reports (
  id uuid primary key default gen_random_uuid(),
  route_id text not null,
  brigadista_id text not null,
  reported_by text,
  block_number integer not null,
  lat double precision,
  lng double precision,
  reported_at timestamptz not null default now(),
  unique(route_id, block_number)
);

create table if not exists public.route_locations (
  id bigint generated by default as identity primary key,
  route_id text not null,
  brigadista_id text not null,
  lat double precision not null,
  lng double precision not null,
  accuracy_m double precision,
  recorded_at timestamptz not null default now()
);

create index if not exists route_reports_route_idx on public.route_reports(route_id, reported_at desc);
create index if not exists route_locations_route_idx on public.route_locations(route_id, recorded_at desc);
create index if not exists route_locations_brigadista_idx on public.route_locations(brigadista_id, recorded_at desc);

-- =========================
-- 2. RLS
-- =========================
alter table public.profiles enable row level security;
alter table public.app_state enable row level security;
alter table public.brigadista_credentials enable row level security;
alter table public.route_runtime enable row level security;
alter table public.route_reports enable row level security;
alter table public.route_locations enable row level security;

-- Solo administradores autenticados pueden leer/escribir directamente los datos internos.
drop policy if exists profiles_admin_all on public.profiles;
create policy profiles_admin_all on public.profiles for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists app_state_admin_all on public.app_state;
create policy app_state_admin_all on public.app_state for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists credentials_admin_all on public.brigadista_credentials;
create policy credentials_admin_all on public.brigadista_credentials for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists runtime_admin_all on public.route_runtime;
create policy runtime_admin_all on public.route_runtime for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists reports_admin_all on public.route_reports;
create policy reports_admin_all on public.route_reports for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists locations_admin_all on public.route_locations;
create policy locations_admin_all on public.route_locations for all to authenticated
using (public.is_admin()) with check (public.is_admin());

-- Revocamos acceso directo anónimo a tablas. Campo opera exclusivamente mediante RPCs SECURITY DEFINER.
revoke all on public.profiles from anon;
revoke all on public.app_state from anon;
revoke all on public.brigadista_credentials from anon;
revoke all on public.route_runtime from anon;
revoke all on public.route_reports from anon;
revoke all on public.route_locations from anon;

grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.app_state to authenticated;
grant select, insert, update, delete on public.brigadista_credentials to authenticated;
grant select, insert, update, delete on public.route_runtime to authenticated;
grant select, insert, update, delete on public.route_reports to authenticated;
grant select, insert, update, delete on public.route_locations to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- =========================
-- 3. HELPERS
-- =========================
create or replace function public._field_pin_ok(p_brigadista_id text, p_pin text)
returns boolean
language sql
stable
security definer
set search_path = public, extensions
as $$
  select exists (
    select 1
    from public.brigadista_credentials b
    where b.brigadista_id = p_brigadista_id
      and b.activo = true
      and b.pin_hash = extensions.crypt(coalesce(p_pin,''), b.pin_hash)
  );
$$;

create or replace function public._route_assigned_to(p_route_id text, p_brigadista_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.app_state s,
         lateral jsonb_array_elements(coalesce(s.state->'journeys','[]'::jsonb)) j,
         lateral jsonb_array_elements(coalesce(j->'exercises','[]'::jsonb)) e,
         lateral jsonb_array_elements(coalesce(e->'routes','[]'::jsonb)) r
    where s.id='main'
      and coalesce((j->>'archived')::boolean,false)=false
      and r->>'id'=p_route_id
      and coalesce(r->'memberIds','[]'::jsonb) ? p_brigadista_id
  );
$$;

create or replace function public._route_goal(p_route_id text)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select greatest(1, coalesce(
    nullif((r->>'blockCount')::numeric,0),
    nullif((r->>'goal')::numeric,0),
    1
  )::integer)
  from public.app_state s,
       lateral jsonb_array_elements(coalesce(s.state->'journeys','[]'::jsonb)) j,
       lateral jsonb_array_elements(coalesce(j->'exercises','[]'::jsonb)) e,
       lateral jsonb_array_elements(coalesce(e->'routes','[]'::jsonb)) r
  where s.id='main' and r->>'id'=p_route_id
  limit 1;
$$;

-- =========================
-- 4. SINCRONIZACIÓN DE CATÁLOGO (ADMIN)
-- =========================
create or replace function public.admin_sync_brigadistas(p_people jsonb)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  p jsonb;
  v_id text;
  v_name text;
  v_active boolean;
  v_pin text;
  v_existing_hash text;
begin
  if not public.is_admin() then raise exception 'No autorizado'; end if;
  if jsonb_typeof(coalesce(p_people,'[]'::jsonb)) <> 'array' then raise exception 'p_people debe ser un arreglo'; end if;

  -- Lo que ya no está en el catálogo queda inactivo, no se elimina: preserva referencias históricas.
  update public.brigadista_credentials set activo=false, updated_at=now();

  for p in select * from jsonb_array_elements(p_people)
  loop
    v_id := p->>'id';
    v_name := p->>'name';
    v_active := coalesce((p->>'active')::boolean,true);
    v_pin := nullif(trim(coalesce(p->>'pin','')),'');
    if v_id is null or v_name is null then continue; end if;

    select pin_hash into v_existing_hash from public.brigadista_credentials where brigadista_id=v_id;
    if v_existing_hash is null then
      if v_pin is null then v_pin := '1234'; end if;
      insert into public.brigadista_credentials(brigadista_id,nombre,activo,pin_hash,updated_at)
      values(v_id,v_name,v_active,extensions.crypt(v_pin,extensions.gen_salt('bf')),now());
    else
      update public.brigadista_credentials
         set nombre=v_name, activo=v_active, updated_at=now(),
             pin_hash=case
               when v_pin is not null and v_existing_hash <> extensions.crypt(v_pin,v_existing_hash)
                 then extensions.crypt(v_pin,extensions.gen_salt('bf'))
               else v_existing_hash
             end
       where brigadista_id=v_id;
    end if;
  end loop;
end;
$$;

-- =========================
-- 5. RPCs PARA BRIGADISTAS
-- =========================
create or replace function public.field_list_brigadistas()
returns table(id text, nombre text)
language sql
stable
security definer
set search_path = public
as $$
  select brigadista_id, nombre
  from public.brigadista_credentials
  where activo=true
  order by nombre;
$$;

create or replace function public.field_get_assignment(p_brigadista_id text, p_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  s jsonb;
  j jsonb;
  e jsonb;
  r jsonb;
  rt public.route_runtime%rowtype;
  reps jsonb;
begin
  if not public._field_pin_ok(p_brigadista_id,p_pin) then raise exception 'PIN incorrecto o brigadista inactivo'; end if;
  select state into s from public.app_state where id='main';
  if s is null then return null; end if;

  select jj,ee,rr into j,e,r
  from jsonb_array_elements(coalesce(s->'journeys','[]'::jsonb)) jj
  cross join lateral jsonb_array_elements(coalesce(jj->'exercises','[]'::jsonb)) ee
  cross join lateral jsonb_array_elements(coalesce(ee->'routes','[]'::jsonb)) rr
  left join public.route_runtime rx on rx.route_id=rr->>'id'
  where coalesce((jj->>'archived')::boolean,false)=false
    and coalesce(rr->'memberIds','[]'::jsonb) ? p_brigadista_id
  order by
    case
      when jj->>'id'=s->>'activeJourneyId' and ee->>'id'=s->>'activeExerciseId' then 0
      when jj->>'id'=s->>'activeJourneyId' then 1
      else 2
    end,
    case when coalesce(rx.status,rr->>'status','pending')='done' then 1 else 0 end,
    ee->>'date', ee->>'time'
  limit 1;

  if r is null then return null; end if;

  select * into rt from public.route_runtime where route_id=r->>'id';
  select coalesce(jsonb_agg(jsonb_build_object(
      'id',id,'number',block_number,'reportedAt',reported_at,'reportedBy',reported_by,
      'brigadistaId',brigadista_id,'lat',lat,'lng',lng
    ) order by reported_at),'[]'::jsonb)
    into reps
  from public.route_reports where route_id=r->>'id';

  r := r || jsonb_build_object(
    'status',coalesce(rt.status,r->>'status','pending'),
    'progress',coalesce(rt.progress,(r->>'progress')::integer,0),
    'completedBlocks',coalesce(rt.completed_blocks,0),
    'completedUnits',coalesce(rt.completed_units,rt.completed_blocks,0),
    'startedAt',rt.started_at,
    'finishedAt',rt.finished_at,
    'lastPosition',rt.last_position,
    'lastPositionAt',rt.last_position_at,
    'lastProgressAt',rt.last_progress_at,
    'blockReports',reps
  );

  return jsonb_build_object(
    'journey',j-'exercises',
    'exercise',e-'routes',
    'route',r
  );
end;
$$;

create or replace function public.field_start_route(p_brigadista_id text, p_pin text, p_route_id text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public._field_pin_ok(p_brigadista_id,p_pin) then raise exception 'PIN incorrecto'; end if;
  if not public._route_assigned_to(p_route_id,p_brigadista_id) then raise exception 'Ruta no asignada'; end if;
  insert into public.route_runtime(route_id,status,started_at,updated_at)
  values(p_route_id,'live',now(),now())
  on conflict(route_id) do update set
    status=case when public.route_runtime.status='done' then 'done' else 'live' end,
    started_at=coalesce(public.route_runtime.started_at,excluded.started_at),
    updated_at=now();
  return true;
end;
$$;

create or replace function public.field_report_block(
  p_brigadista_id text, p_pin text, p_route_id text,
  p_lat double precision default null, p_lng double precision default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_goal integer;
  v_done integer;
  v_progress integer;
  v_name text;
begin
  if not public._field_pin_ok(p_brigadista_id,p_pin) then raise exception 'PIN incorrecto'; end if;
  if not public._route_assigned_to(p_route_id,p_brigadista_id) then raise exception 'Ruta no asignada'; end if;
  select nombre into v_name from public.brigadista_credentials where brigadista_id=p_brigadista_id;
  v_goal := public._route_goal(p_route_id);

  insert into public.route_runtime(route_id,status,started_at,updated_at)
  values(p_route_id,'live',now(),now())
  on conflict(route_id) do nothing;

  select completed_blocks into v_done from public.route_runtime where route_id=p_route_id for update;
  if (select status from public.route_runtime where route_id=p_route_id)='done' then raise exception 'Ruta finalizada'; end if;
  v_done := least(v_goal,coalesce(v_done,0)+1);
  v_progress := least(100,round((v_done::numeric/v_goal::numeric)*100)::integer);

  insert into public.route_reports(route_id,brigadista_id,reported_by,block_number,lat,lng)
  values(p_route_id,p_brigadista_id,v_name,v_done,p_lat,p_lng)
  on conflict(route_id,block_number) do nothing;

  update public.route_runtime set completed_blocks=v_done,completed_units=v_done,progress=v_progress,last_progress_at=now(),updated_at=now() where route_id=p_route_id;
  return jsonb_build_object('completedBlocks',v_done,'progress',v_progress);
end;
$$;

create or replace function public.field_report_progress(p_brigadista_id text, p_pin text, p_route_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_progress integer;
  v_goal numeric;
  v_units numeric;
begin
  if not public._field_pin_ok(p_brigadista_id,p_pin) then raise exception 'PIN incorrecto'; end if;
  if not public._route_assigned_to(p_route_id,p_brigadista_id) then raise exception 'Ruta no asignada'; end if;
  select coalesce((r->>'goal')::numeric,1) into v_goal
  from public.app_state s,
       lateral jsonb_array_elements(coalesce(s.state->'journeys','[]'::jsonb)) j,
       lateral jsonb_array_elements(coalesce(j->'exercises','[]'::jsonb)) e,
       lateral jsonb_array_elements(coalesce(e->'routes','[]'::jsonb)) r
  where s.id='main' and r->>'id'=p_route_id limit 1;
  insert into public.route_runtime(route_id,status,started_at,updated_at)
  values(p_route_id,'live',now(),now()) on conflict(route_id) do nothing;
  if (select status from public.route_runtime where route_id=p_route_id)='done' then raise exception 'Ruta finalizada'; end if;
  select least(100,coalesce(progress,0)+10) into v_progress from public.route_runtime where route_id=p_route_id for update;
  v_units := coalesce(v_goal,1) * v_progress / 100.0;
  update public.route_runtime set progress=v_progress,completed_units=v_units,last_progress_at=now(),updated_at=now() where route_id=p_route_id;
  return jsonb_build_object('progress',v_progress,'completedUnits',v_units);
end;
$$;

create or replace function public.field_update_location(
  p_brigadista_id text, p_pin text, p_route_id text,
  p_lat double precision, p_lng double precision, p_accuracy_m double precision default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public._field_pin_ok(p_brigadista_id,p_pin) then raise exception 'PIN incorrecto'; end if;
  if not public._route_assigned_to(p_route_id,p_brigadista_id) then raise exception 'Ruta no asignada'; end if;
  insert into public.route_locations(route_id,brigadista_id,lat,lng,accuracy_m) values(p_route_id,p_brigadista_id,p_lat,p_lng,p_accuracy_m);
  insert into public.route_runtime(route_id,status,last_position,last_position_at,updated_at)
  values(p_route_id,'live',jsonb_build_object('lat',p_lat,'lng',p_lng,'accuracy',p_accuracy_m),now(),now())
  on conflict(route_id) do update set last_position=excluded.last_position,last_position_at=excluded.last_position_at,updated_at=now();
  return true;
end;
$$;

create or replace function public.field_finish_route(p_brigadista_id text, p_pin text, p_route_id text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_goal integer;
  v_done integer;
  v_progress integer;
begin
  if not public._field_pin_ok(p_brigadista_id,p_pin) then raise exception 'PIN incorrecto'; end if;
  if not public._route_assigned_to(p_route_id,p_brigadista_id) then raise exception 'Ruta no asignada'; end if;
  v_goal := public._route_goal(p_route_id);
  select coalesce(completed_blocks,0) into v_done from public.route_runtime where route_id=p_route_id;
  v_progress := case when v_goal>0 then least(100,round((coalesce(v_done,0)::numeric/v_goal::numeric)*100)::integer) else 100 end;
  insert into public.route_runtime(route_id,status,completed_blocks,progress,finished_at,updated_at)
  values(p_route_id,'done',coalesce(v_done,0),v_progress,now(),now())
  on conflict(route_id) do update set status='done',progress=v_progress,finished_at=now(),updated_at=now();
  return true;
end;
$$;

-- Permisos de RPC: el catálogo y las operaciones de campo se exponen solo a través de funciones validadas por PIN.
-- Las funciones no quedan ejecutables por PUBLIC de forma implícita.
revoke all on function public._field_pin_ok(text,text) from public;
revoke all on function public._route_assigned_to(text,text) from public;
revoke all on function public._route_goal(text) from public;
revoke all on function public.admin_sync_brigadistas(jsonb) from public;
revoke all on function public.field_list_brigadistas() from public;
revoke all on function public.field_get_assignment(text,text) from public;
revoke all on function public.field_start_route(text,text,text) from public;
revoke all on function public.field_report_block(text,text,text,double precision,double precision) from public;
revoke all on function public.field_report_progress(text,text,text) from public;
revoke all on function public.field_update_location(text,text,text,double precision,double precision,double precision) from public;
revoke all on function public.field_finish_route(text,text,text) from public;

grant execute on function public.field_list_brigadistas() to anon, authenticated;
grant execute on function public.field_get_assignment(text,text) to anon, authenticated;
grant execute on function public.field_start_route(text,text,text) to anon, authenticated;
grant execute on function public.field_report_block(text,text,text,double precision,double precision) to anon, authenticated;
grant execute on function public.field_report_progress(text,text,text) to anon, authenticated;
grant execute on function public.field_update_location(text,text,text,double precision,double precision,double precision) to anon, authenticated;
grant execute on function public.field_finish_route(text,text,text) to anon, authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.admin_sync_brigadistas(jsonb) to authenticated;

-- =========================
-- 6. REALTIME
-- =========================
-- Idempotente: solo agrega si aún no forma parte de la publicación.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='app_state') then execute 'alter publication supabase_realtime add table public.app_state'; end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='route_runtime') then execute 'alter publication supabase_realtime add table public.route_runtime'; end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='route_reports') then execute 'alter publication supabase_realtime add table public.route_reports'; end if;
end $$;

-- =========================
-- 7. CREAR EL PRIMER ADMIN
-- =========================
-- Primero crea el usuario desde Authentication > Users en el dashboard de Supabase.
-- Después sustituye TU_CORREO y ejecuta SOLO esta sentencia:
-- insert into public.profiles(user_id,role)
-- select id,'admin' from auth.users where email='TU_CORREO@dominio.com'
-- on conflict(user_id) do update set role='admin';
